repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # Use the latest stable version or a specific version
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287  # Use the latest stable version or a specific version
    hooks:
      - id: ruff
        args: [--fix]
        language_version: python3.11
